import type { Metadata, Viewport } from 'next';
import { Open_Sans } from 'next/font/google';

import './globals.css';
import ContextProvider from '@/lib/context';
import Layout from '@/components/common/Layout';

export const metadata: Metadata = {
  title: {
    default: 'Home',
    template: '%s | Next Realworld'
  },
  description: 'Generated by vicky'
};

const sans = Open_Sans({ subsets: ['latin'] });
export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 1,
  userScalable: false
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={sans.className}>
        <ContextProvider>
          <Layout>{children}</Layout>
        </ContextProvider>
      </body>
    </html>
  );
}
