import type { Metadata, Viewport } from 'next';

import './globals.css';
import ContextProvider from '@/lib/context';
import Layout from '@/components/common/Layout';
import Head from 'next/head';
import localFont from 'next/font/local';

import 'https://demo.productionready.io/main.css';

export const metadata: Metadata = {
  title: {
    default: 'Home',
    template: '%s | Next Realworld'
  },
  description: 'Generated by vicky'
};

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 1,
  userScalable: false
};

const pretendard = localFont({
  src: '../../public/static/fonts/PretendardVariable.woff2',
  display: 'swap',
  weight: '45 920',
  variable: '--font-pretendard'
});

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${pretendard.variable}`}>
      <body className={pretendard.className}>
        <link
          rel="stylesheet"
          href="https://demo.productionready.io/main.css"
        />
        <link
          rel="stylesheet"
          href="//code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css"
        />
        <ContextProvider>
          <Layout>{children}</Layout>
        </ContextProvider>
      </body>
    </html>
  );
}
